SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MenuRights](
	[menuRightsId] [int] NOT NULL,
	[menuItemId] [int] NULL,
	[empRoleId] [nchar](10) NULL,
 CONSTRAINT [PK_MenuRights] PRIMARY KEY CLUSTERED 
(
	[menuRightsId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO